import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#140c28] p-4">
        <main
          className={`${quicksand.variable} font-quicksand max-w-[900px] w-full m-auto flex flex-col items-center`}
        >
          <h1 className="mt-4 text-3xl font-bold leading-none tracking-tight  md:text-4xl lg:text-5xl text-white">
            BrainBurst Quiz
          </h1>
          {children}
        </main>
      </body>
    </html>
  );
}
